# fly.toml app configuration file generated for app-grader on 2024-02-20T22:24:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-grader'
primary_region = 'bos'

[build]

[[mounts]]
  source="data"
  destination="/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
